version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: dockerfile
    container_name: php-app
    ports:
      - "8080:80" # ローカルPCの8080 → コンテナ内の80（Apache）
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/html/src
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306" # 通常PHPコードやツールが使うポート（ブラウザ不可）
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_pass
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./public/default.conf:/etc/apache2/sites-available/000-default.conf
